### ISSUE TITLE
Right side of ui goes further then i can see

### ISSUE THREAD

**Issue by 111ebobo** [soup-bowl/Modoki-Firefox#17] opened 2023-04-30 08:57 UTC

**Comment by 111ebobo** [comment] 2023-04-30 08:57
![Записати](https://user-images.githubusercontent.com/104251188/235344629-63be6585-cf19-49b2-bc34-9e746f3265e1.PNG)

**Comment by soup-bowl** [comment] 2023-04-30 14:21
Duplicate of #8

**Closed by soup-bowl** 2023-04-30 14:21 UTC
